server:
   port: 8888
   
spring:
   application:
      name: config-server-demo
   cloud:
      config:
         server:
            git:
               uri: https://github.com/micjerry/spconfigdemo.git
               username: hansfei@126.com
               password: xfXF1981gh
               default-label: master
               search-paths: config
               